  /// \file RawCaloHitHandler.cc
/*
 *
 * RawCaloHitHandler.cc source template automatically generated by a class generator
 * Creation date : sam. f�vr. 20 2016
 *
 * This file is part of xdrlcio libraries.
 * 
 * xdrlcio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * xdrlcio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with xdrlcio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "xdrlcio/RawCaloHitHandler.h"

#include "IOIMPL/RawCalorimeterHitIOImpl.h"
#include "IMPL/LCFlagImpl.h"
#include "EVENT/LCIO.h"

namespace xdrlcio
{

class XdrRawCaloHit : public IOIMPL::RawCalorimeterHitIOImpl
{
	friend class RawCaloHitHandler;
};

//----------------------------------------------------------------------------------------------------
//----------------------------------------------------------------------------------------------------

xdrstream::Status RawCaloHitHandler::read(xdrstream::IODevice *pDevice, EVENT::LCObject *&pLCObject)
{
	XdrRawCaloHit *pCaloHit = new XdrRawCaloHit();
	pLCObject = pCaloHit;

	IMPL::LCFlagImpl lcFlag( m_lcFlag );

	XDR_STREAM( pDevice->read<int32_t>( & pCaloHit->_cellID0 ) )

	if( lcFlag.bitSet( EVENT::LCIO::RCHBIT_ID1 ) )
		XDR_STREAM( pDevice->read<int32_t>( & pCaloHit->_cellID1 ) )

	XDR_STREAM( pDevice->read<int32_t>( & pCaloHit->_amplitude ) )

	if( lcFlag.bitSet( EVENT::LCIO::RCHBIT_TIME ) )
		XDR_STREAM( pDevice->read<int32_t>( & pCaloHit->_timeStamp ) )

	if( ! lcFlag.bitSet( EVENT::LCIO::RCHBIT_NO_PTR ) )
		XDR_STREAM( pDevice->readPointerTag( (void *) pCaloHit ) )

	return xdrstream::XDR_SUCCESS;
}

//----------------------------------------------------------------------------------------------------

xdrstream::Status RawCaloHitHandler::write(xdrstream::IODevice *pDevice, const EVENT::LCObject *const pLCObject)
{
	const EVENT::RawCalorimeterHit *const pCaloHit = dynamic_cast<const EVENT::RawCalorimeterHit *>( pLCObject );

	IMPL::LCFlagImpl lcFlag( m_lcFlag );

	int32_t cellID0 = pCaloHit->getCellID0();
	XDR_STREAM( pDevice->write<int32_t>( & cellID0 ) )

	if( lcFlag.bitSet( EVENT::LCIO::RCHBIT_ID1 ) )
	{
		int32_t cellID1 = pCaloHit->getCellID1();
		XDR_STREAM( pDevice->write<int32_t>( & cellID1 ) )
	}

	int32_t amplitude = pCaloHit->getAmplitude();
	XDR_STREAM( pDevice->write<int32_t>( & amplitude ) )

	if( lcFlag.bitSet( EVENT::LCIO::RCHBIT_TIME ) )
	{
		int32_t timeStamp = pCaloHit->getTimeStamp();
		XDR_STREAM( pDevice->write<int32_t>( & timeStamp ) )
	}

	if( ! lcFlag.bitSet( EVENT::LCIO::RCHBIT_NO_PTR ) )
		XDR_STREAM( pDevice->writePointerTag( (void *) pCaloHit ) )

	return xdrstream::XDR_SUCCESS;
}

} 

