  /// \file LCObjectHandlerMgr.h
/*
 *
 * LCObjectHandlerMgr.h header template automatically generated by a class generator
 * Creation date : ven. f�vr. 12 2016
 *
 * This file is part of xdrlcio libraries.
 * 
 * xdrlcio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * xdrlcio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with xdrlcio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef LCOBJECTHANDLERMGR_H
#define LCOBJECTHANDLERMGR_H

// -- std headers
#include <string>
#include <map>

// -- xdrlcio headers
#include "xdrlcio/LCObjectHandler.h"

namespace xdrlcio
{

/**
 * @brief LCObjectHandlerMgr class
 */ 
class LCObjectHandlerMgr 
{
public:
	/**
	 *  @brief  Constructor
	 */
	LCObjectHandlerMgr();

	/**
	 *  @brief  Destructor
	 */
	~LCObjectHandlerMgr();

	/**
	 *  @brief
	 */
	bool addHandler( const std::string &handlerName , LCObjectHandler *pHandler );

	/**
	 *  @brief
	 */
	LCObjectHandler *getHandler( const std::string &handlerName ) const;

private:
	std::map<std::string, LCObjectHandler *>        m_objectHandlerMap;
}; 

} 

#endif  //  LCOBJECTHANDLERMGR_H
