  /// \file ParticleIDHandler.h
/*
 *
 * ParticleIDHandler.h header template automatically generated by a class generator
 * Creation date : mer. f�vr. 17 2016
 *
 * This file is part of xdrlcio libraries.
 * 
 * xdrlcio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * xdrlcio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with xdrlcio.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef PARTICLEIDHANDLER_H
#define PARTICLEIDHANDLER_H

// -- xdrstream headers
#include "xdrstream/xdrstream.h"

// -- lcio headers
#include "IOIMPL/ParticleIDIOImpl.h"

namespace xdrlcio
{

class ParticleIDHandler;

class XdrParticleID : public IOIMPL::ParticleIDIOImpl
{
	friend class ParticleIDHandler;
};

/** 
 * @brief ParticleIDHandler class
 */ 
class ParticleIDHandler
{
public:
	/**
	 *  @brief
	 */
	static xdrstream::Status read(xdrstream::IODevice *pDevice, EVENT::ParticleID *&pParticleID , xdrstream::xdr_version_t version);

	/**
	 *  @brief
	 */
	static xdrstream::Status write(xdrstream::IODevice *pDevice, const EVENT::ParticleID *pParticleID);
}; 

} 

#endif  //  PARTICLEIDHANDLER_H
